# Generated by Django 2.2 on 2021-12-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_number', models.CharField(max_length=32, unique=True, verbose_name='需求编号')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '待审核'), (2, '待评估'), (3, '评估中'), (4, '待开发'), (5, '开发中'), (6, '放弃需求'), (7, '已完成')], default=11, verbose_name='状态')),
                ('sponsor', models.CharField(default='', max_length=16, verbose_name='发起人')),
                ('department', models.CharField(default='', max_length=32, verbose_name='部门')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('demand_type', models.PositiveSmallIntegerField(choices=[(1, '新增功能'), (2, '功能变更'), (3, '功能舍弃'), (4, '问题')], default=1, verbose_name='需求类型')),
                ('demand_describe', models.CharField(default='', max_length=500, verbose_name='需求描述')),
                ('urgent_degree', models.PositiveSmallIntegerField(choices=[(1, '紧急'), (0, '不紧急')], default=0, verbose_name='紧急程度')),
                ('important_degree', models.PositiveSmallIntegerField(choices=[(1, '重要'), (0, '不重要')], default=0, verbose_name='重要程度')),
                ('file', models.ImageField(blank=True, null=True, upload_to='demand_images/', verbose_name='相关截图')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('develop_cycle', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='预计开发周期')),
            ],
            options={
                'verbose_name': '需求管理',
                'verbose_name_plural': '需求管理',
                'ordering': ['-create_date'],
            },
        ),
    ]
