# Generated by Django 2.2 on 2021-12-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demands',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待审核'), (2, '待评估'), (3, '评估中'), (4, '待开发'), (5, '开发中'), (6, '放弃需求'), (7, '已完成')], default=1, verbose_name='状态'),
        ),
    ]
