# Generated by Django 2.2 on 2021-12-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manage', '0002_auto_20211223_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demands',
            options={'ordering': ['-create_time'], 'verbose_name': '需求管理', 'verbose_name_plural': '需求管理'},
        ),
        migrations.RenameField(
            model_name='demands',
            old_name='create_date',
            new_name='create_time',
        ),
    ]
