# Generated by Django 2.2 on 2022-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manage', '0003_auto_20211224_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_number', models.CharField(max_length=32, unique=True, verbose_name='需求编号')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '待审核'), (2, '已审核'), (3, '审核中'), (4, '已退回')], default=1, verbose_name='状态')),
                ('sponsor', models.CharField(default='', max_length=16, verbose_name='提出人')),
                ('department', models.CharField(default='', max_length=32, verbose_name='部门')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提出时间')),
                ('demand_type', models.PositiveSmallIntegerField(choices=[(1, '新增功能'), (2, '功能变更'), (3, '功能舍弃'), (4, '问题')], default=1, verbose_name='需求类型')),
                ('demand_describe', models.CharField(default='', max_length=500, verbose_name='需求描述')),
                ('urgent_degree', models.PositiveSmallIntegerField(choices=[(0, '不紧急'), (1, '紧急')], default=0, verbose_name='紧急程度')),
                ('important_degree', models.PositiveSmallIntegerField(choices=[(0, '不重要'), (1, '重要')], default=0, verbose_name='重要程度')),
                ('file', models.ImageField(blank=True, null=True, upload_to='demand_images/', verbose_name='相关截图')),
                ('verify_result', models.PositiveSmallIntegerField(choices=[(1, '确定要做'), (2, '确定不做'), (3, '再想想'), (4, '退回')], default=1, verbose_name='审核结果')),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='审核建议')),
            ],
            options={
                'verbose_name': '需求梳理',
                'verbose_name_plural': '需求梳理',
                'ordering': ['-create_time'],
            },
        ),
        migrations.DeleteModel(
            name='Demands',
        ),
    ]
