# Generated by Django 2.2 on 2022-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manage', '0004_auto_20220110_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcollect',
            name='verify_result',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '确定要做'), (2, '确定不做'), (3, '再想想'), (4, '退回')], default=0, verbose_name='审核结果'),
        ),
    ]
