# Generated by Django 2.2 on 2022-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manage', '0005_auto_20220110_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcollect',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待审核'), (2, '已审核'), (3, '已退回')], default=1, verbose_name='状态'),
        ),
    ]
