# Generated by Django 2.2 on 2022-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_manage', '0007_demanddesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanddesign',
            name='estimate_result',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '通过'), (2, '退回'), (3, '暂缓')], default=0, verbose_name='评估结果'),
        ),
    ]
